---
title: "Analytics graphs - Bar Charts"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <- read.csv('/Users/suzyg./Desktop/fall2019-proj2--sec1-grp8/data/fuel station data/alt_fuel_stations .csv')
dim(data)
```


```{r}
library('dplyr')
library('plotly')
library('tidyr')
```


```{r}
#plot1: station distribution by state
grouped_states <- group_by(data,State)
count_state = summarise(grouped_states, count=n())

p1 <- plot_ly(count_state,
  x=~reorder(State,count),
  y=~count,
  type ='bar')%>%
  layout(title = 'Alternative Fuel Station Distritbution in the US')

p1
```


```{r}
#plot2: fuel type count

data$fueltype = as.character(data$Fuel.Type.Code)
data$fueltype[data$fueltype == "ELEC"] <- "Electric"
data$fueltype[data$fueltype == "CNG"] <- 'Compressed Natural Gas'
data$fueltype[data$fueltype == "BD"] <- 'Biodiesel (B20 and above)'
data$fueltype[data$fueltype == "E85"] <- 'Ethanol (E85)'
data$fueltype[data$fueltype == "HY"] <- 'Hydrogen'
data$fueltype[data$fueltype == "LNG"] <- 'Liquefied Natural Gas'
data$fueltype[data$fueltype == "LPG"] <- 'Liquefied Petroleum Gas (Propane)'


grouped_fuel <- group_by(data,fueltype)
count_fuel = summarise(grouped_fuel,count=n())

p2_1 <- plot_ly(count_fuel,x=~fueltype, y=~count,type='bar',marker = list(color = c('rgba(204,204,204,1)','rgba(204,204,204,1)','rgba(222,45,38,0.8)',                                                                'rgba(204,204,204,1)','rgba(204,204,204,1)',                                                                        'rgba(204,204,204,1)','rgba(204,204,204,1)')))%>%
  layout(title = 'Count of Alternative Fuel',
         xaxis = list(
      type = 'category',
      title = 'Fuel Type'))

p2_1
```




```{r}
# plot3: state vs fuel type
state_type = summarise(group_by(data,State,fueltype),count =n())
p3 <- plot_ly(state_type, x = ~State, y = ~count, color=~fueltype, type = 'bar')%>%
  layout(title = 'Fuel Type Distribution by State')

p3
```

```{r}
# plot 4: Comparing Fuel Type Distribution between Top 2 States
# compare top 2 states with the most stations and see how fuel type distributed in two states
# from plot 2, top 2 states are: CA, TX

ca = state_type$count[state_type$State =='CA']
tx = state_type$count[state_type$State =='TX']

fueltype = c('Biodiesel (B20 and above)',"Compressed Natural Gas","Electric",
             "Ethanol (E85)","Hydrogen",
             "Liquefied Natural Gas","Liquefied Petroleum Gas (Propane)")

df <- data.frame(fueltype,ca,tx)

p <- plot_ly(df, x = ~fueltype, y = ~ca, type = 'bar', name = 'CA') %>%
  add_trace(y = ~tx, name = 'TX') %>%
  layout(title = 'Comparing Fuel Type Distribution between Top 2 States',
         yaxis = list(title = 'Count'), barmode = 'stack')

p
```




```{r}

forcats::fct_count(data$Groups.With.Access.Code)
data$Groups.With.Access.Code <- forcats::fct_collapse(data$Groups.With.Access.Code,
                         planned = c("PLANNED - not yet accessible (Private - Fleet customers only)",
                                     "PLANNED - not yet accessible (Private - Government only)",
                                     "PLANNED - not yet accessible (Private)",
                                     "PLANNED - not yet accessible (Public - Call ahead)",
                                     "PLANNED - not yet accessible (Public - Card key at all times)",
                                     "PLANNED - not yet accessible (Public - Credit card at all times)",
                                     "PLANNED - not yet accessible (Public)"),
                         private = c("Private",
                                     "Private - Call ahead",
                                     "Private - Card key at all times",
                                     "Private - Fleet customers only",
                                     "Private - Government only" 
                                     ),
                         public = c("Public","Public - Call ahead","Public - Card key at all times",
                                    "Public - Credit card after hours","Public - Credit card at all times",
                                    "Public - Fleet customers only",
                                    "Public - Card key after hours"),
                         temp_unavailable = c("TEMPORARILY UNAVAILABLE (Private - Government only)",
                         "TEMPORARILY UNAVAILABLE (Private)",
                         "TEMPORARILY UNAVAILABLE (Public - Call ahead)",
                         "TEMPORARILY UNAVAILABLE (Public - Card key at all times)",
                         "TEMPORARILY UNAVAILABLE (Public - Credit card after hours)",
                         "TEMPORARILY UNAVAILABLE (Public - Credit card at all times)",
                         "TEMPORARILY UNAVAILABLE (Public)"))
                         

levels(data$Groups.With.Access.Code)
```


```{r}
# plot4

state_access = summarise(group_by(data,State,Access.Code),count =n())
p4 <- plot_ly(state_access, x = ~State, y = ~count, color = ~Access.Code,type = 'bar')%>%
  layout(title = 'Access By State')

p4
```



```{r}
#plot5
access_type = summarise(group_by(data,Access.Code,fueltype), count=n())
p5 <- plot_ly(access_type, x=~Access.Code, y=~count, color=~fueltype)%>%
  layout(title = 'Fuel Type by Access',
         xaxis = list(title='Access Type'))
  

p5

```


```{r}
#plot6

p6 <- plot_ly(access_type, x=~fueltype, y=~count, color=~Access.Code)%>%
  layout(title = 'Access By Fuel Type')

p6
```









