---
title: "plot+function"
author: "Yiwen Ma"
date: "10/5/2019"
output: html_document
---

```{r}
library(gbutils)
library(readr)
library(dplyr)
library(plotly)
library(pracma)
alt_fuel_stations <- read.csv("data/alt_fuel_stations.csv")

#Group the data by fuel type and year. 
#For missing value in "Open date", fill it with the number in "Latest Confirmed Date"
 alt_fuel_stations<- data.frame(alt_fuel_stations) 
station_date <- alt_fuel_stations %>% select(Fuel.Type.Code, Date.Last.Confirmed, Open.Date)
fillNA <- function(x, y) {
  if (isNA(x)) {y} else {x}
}
station_date$`Year` <- format(as.Date(apply(station_date[,c("Open.Date","Date.Last.Confirmed")],1,function(x) fillNA(x[1],x[2]))),"%Y")

# Due to the existance of outliers (BD)in last few year, thus a natural log is used to make the plot more readable.
countGB <- station_date %>% group_by(Fuel.Type.Code, Year) %>% summarise(Count = log(n()))
p <- plot_ly(countGB, x=~Year, y=~Count, color=~Fuel.Type.Code) %>% add_lines()
p
```

```{r}
# param o:start point in 2d
# param d:end point in 2d
# param seg:number of line segments wanted
# return:(seg+1) by 2 matrix with cutoff points
segment2d <- function (o,d,seg) {
  segdim1 <- linspace(o[1],d[1],seg+1)
  segdim2 <- linspace(o[2],d[2],seg+1)
  return(cbind(segdim1,segdim2))
}

# param l: a dataframe with two cols (long,lat)
# param orig: origination coordinates (long, lat)
# param dest: destination coordinates (long, lat)
# param firstn: number of outputs
# return: calculate the perpendicular distances to the line (orig, dest), return argsorted indices of coordinate within the rectangle formed by orig and dest
# orig, dest: (longitude, latitude)
distToLine <- function(l,orig,dest,firstn) {
  mat <- data.matrix(l)
  v1 <- orig - dest
  deno <- sqrt(sum(v1*v1))
  
  distToLineSingle <- function(p,o,d,v1,deno) {
    if (p[1] > max(c(o[1],d[1])) | p[1] < min(c(o[1],d[1])) | 
        p[2] > max(c(o[2],d[2])) | p[2] < min(c(o[2],d[2]))) {return(Inf)}
    v2 <- p - o
    m <- cbind(v1,v2)
    return(abs(det(m))/deno)
  }
  dist <- apply(mat,1,distToLineSingle,o=orig,d=dest,v1=v1,deno=deno)
  numInf <- length(dist[dist=Inf])
  return(head(head(order(unlist(dist)),n=-numInf),n=firstn))
}

# segment routes into 'seg' segments and find nearest 'firstn' stations in each segment, return unique indices (argsort)
segRoute <- function(l, orig, dest, seg, firstn) {
  station <- c()
  segList <- segment2d(orig,dest,seg)
  for (i in 1:(seg)) {
    station <- c(station,distToLine(l,segList[i,],segList[i+1,],firstn))
  }
  return(unique(station))
}
```


```{r}
#example test case
stationName <- alt_fuel_stations$Station.Name
stationCity <- alt_fuel_stations$City
stationState <- alt_fuel_stations$State
coords <- data.matrix(select(alt_fuel_stations,Longitude,Latitude))
o <- c(-73.954909,40.755764)
d <- c(-95.35,29.749907)
s <- segRoute(coords,o,d,5,2)
stationName[s]
stationCity[s]
stationState[s]
```


