---
title: "app"
author: "Daniel Lee"
date: "9/28/2019"
output: html_document
---


```{r}
ui <- dashboardPage(
  dashboardHeader(title = "NYC Park Party"),
  dashboardSidebar(
    sidebarMenu(
    menuItem("Map", tabName = "mapping", icon = icon("map")),
    menuItem("Chlo", icon = icon("th"), tabName = "chlo"))
  ),
  dashboardBody(
    tabItems(
      tabItem(
        tabName= "mapping",
        fluidRow(
          box(leafletOutput("plot1", height = 500)),
          box(
              selectInput(inputId = "borough",
                    label= "Borough",
                    choices = unique(parks$borough))),
          box(
             sliderInput("range", "Time Range:",
                  min = 0, max = 24,
                  value = c(1,10)))
    )
    ),
     tabItem(
      tabName = "chlo",
      fluidRow(
        box(leafletOutput("chlomap", height = 500)))
    )
  )
  )
)


server <- function(input, output) {
  output$plot1 <- renderLeaflet({
    rows <- which(parks$borough == input$borough)
    data <- parks[rows,]
    leaflet(data) %>%
      addTiles() %>%
      addCircleMarkers(lng = ~long, 
                   lat = ~lat, 
                   popup = ~name,
                   stroke = FALSE,
                   radius = 5,
                   fillOpacity = 0.5,
                   label = ~title
                   )
  })
  #cholorpleth
  output$plot2 <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      setView(-74.00, 40.71, zoom = 12) %>%
      addProviderTiles("CartoDB.Positron")
  })
}

shinyApp(ui, server)
```


# ALT FUEL
```{r}
#altfuel
altfuel <- altfuel[altfuel$Country == "US",]
alt <- head(altfuel,5000)
fuel_price <- matrix(nrow=1,ncol=7)
fuel_price[1,] <- c(2.19, 1.99, 2, 2.71, 2.91, 2.8, 13)
colnames(fuel_price) <- c("CNG","E85","ELEC","LNG","LPG","BD","HY")
fuel_price <- as.data.frame(fuel_price)
# electric: If electricity costs $0.11 per kilowatt-hour, charging an all-electric vehicle with a 70-mile range (assuming a fully depleted 24 kWh battery) will cost about $2.64 to reach a full charge.
```

```{r}
ui <- 
  dashboardPage(
  dashboardHeader(title = "Alternative fuel"),
  dashboardSidebar(
    sidebarMenu(
    menuItem("Map", tabName = "navigation", icon = icon("map")),
    menuItem("Calculate", icon = icon("calculator"), tabName = "calculate"),
    menuItem("Analytics", icon = icon("stocks"), tabName = "analytics"),
    menuItem("Directory", icon = icon("book"), tabName = "directory")
    )
  ),
  dashboardBody(
    tabItems(
        tabItem(
          tabName= "navigation",
          navbarPage(
            "Tools :",
            tabPanel(
              "Navigate",
      fluidRow(
        box(leafletOutput("nav")),
        box(selectInput(inputId = "nav_fuel_type",
                    label= "Fuel type",
                    choices = unique(altfuel$Fuel.Type.Code))),
        box(textInput(h3("Currnet Location"),inputId = "address")),
        box(submitButton("Locate me")),
        box(sliderInput(inputId = "range", "Radius Range:",
                  min = 0, max = 100, value = 6))
              )
        )
        )
        ),
    tabItem(
      tabName = "calculate",
      navbarPage(
        "Calculators",
        tabPanel(
          "Alt fuels",
      fluidRow(
          box(
            h4("Average price"), height = 350,
            plotOutput(outputId = "fuel_table1", width = "50%", height="200px")),
          box(
            h4("Average price by EEF"), height = 350,
            plotOutput(outputId = "fuel_table2", width = "50%", height="200px")),
           box(
             numericInput(h3("Tank size"),value = 1, inputId = "tank"),
               textOutput("fuel_description")),
           box(
              selectInput(inputId = "fuel_price",
                    label= "Fuel type",
                    choices = unique(altfuel$Fuel.Type.Code)),
                    submitButton("Calculate"))),
           box(
             h3("Estimated:"),
             textOutput("calc_result"))
      ),
        tabPanel(
          "Gasoline",
          fluidPage(
            fluidRow(
            textInput(inputId = "start_point","Start"),
            textInput(inputId = "end_point","Destination")
          ),
            fluidRow(
              selectInput(inputId = "car_brand","Manufacturer",
                          choices = unique(car_data$Manufacturer)),
              selectInput(inputId = "car_year","Year",
                          choices = unique(car_data$Model.Year)),
              selectizeInput(inputId = 'model_selection', 
                             label = "Model", choices = unique(car_data$Model),
                             selected = NULL,
                             options = list(maxOptions=10, create = TRUE),
              ),
              submitButton("Calculate"),
              box(textOutput("gasoline_calc"))
            )
        )
      )
      )
      ),

    tabItem(tabName = "analytics",
            navbarPage(
              "Analytics",
              tabPanel(
                "Bar chart",
            fluidRow(
            plotlyOutput("analytics")
            #textInput(h3("Which State?"), inputId ="anal_fuel_type") 
                    )
            ),
              tabPanel(
                "Heatmap",
                fluidRow(
                   leafletOutput("heatmap"),
                   selectInput(inputId = "heat_fuel_type",
                               label= "Fuel type",
                              choices = c("All",as.character(unique(altfuel$Fuel.Type.Code)))),
                   submitButton("Go!")
                      )
                    ),
              tabPanel(
                "Animation",
                fluidRow(
                  leafletOutput("animate"),
                  sliderInput(inputId = "heat_years",
                              label="Years",
                              min = 1953, max = 2019, value=2000,
                              animate=animationOptions(interval = 50))
                )
              )
            )
    ),
    tabItem(
      tabName = "directory",
      fluidRow(
        h3("Directory"),
          dataTableOutput("directory")
      )
    )
    )
  )
)



server <- function(input, output) {
  pal <- colorFactor(c("indianred", "yellow", "lightsalmon", "palegreen", "gray74", "lightpink", "cornflowerblue"), domain = unique(altfuel$station_type)) # color palette by fuel type

  output$plot1 <- renderLeaflet({
    altrows <- which(alt$Fuel.Type.Code == input$fuel_type)
    data <- alt[altrows,]
    leaflet(data) %>%
      addTiles() %>%
      addCircleMarkers(lng = ~Longitude, 
                   lat = ~Latitude, 
                   popup = paste(
                     "Name:", alt$Station.Name, "<br>",
                     "Address:", alt$Street.Address, "<br>",
                     "Phone #:", alt$Station.Phone, "<br>"
                   ),
                   stroke = FALSE,
                   radius = 5,
                   fillOpacity = 0.7
                   )
  })
  
  #cholorpleth
  output$heatmap <- renderLeaflet({
    heatrows <- which(alt$Fuel.Type.Code == input$heat_fuel_type)
    heatdata <- alt[heatrows,]
    if(input$heat_fuel_type == "All"){
      leaflet(alt) %>%
        addProviderTiles("CartoDB.Positron") %>%
        addHeatmap(blur = 20, max = 0.05, radius = 15)
    }
    else{
    leaflet(heatdata) %>%
      addProviderTiles("CartoDB.Positron") %>%
      addHeatmap(blur = 20, max = 0.05, radius = 15)
    }
  })
  
  output$calc_result <- renderText({
    fuel_price[1,input$fuel_price] * input$tank
  })
  output$fuel_table1 <- renderImage({
    filename <- normalizePath(file.path('./table2.png'))
    list(src = filename, width = "300px", height="300px")
  }, deleteFile = FALSE)
  output$fuel_table2 <- renderImage({
    filename <- normalizePath(file.path('./table3.png'))
    list(src = filename, width = "300px", height="300px")
  }, deleteFile = FALSE)
  output$fuel_description <- renderText({
     "CNG(per GGE), LNG(per DGE), E85,BD: per Gallon, Hydrogen(per Kg)"
  })
  output$nav <- renderLeaflet({
    navrows <- which(alt$Fuel.Type.Code == input$nav_fuel_type)
    navdata <- alt[navrows,]
    current_loc <- geocode(input$address)
    leaflet(navdata) %>%
      addTiles() %>%
      addCircleMarkers(lng = ~Longitude, 
                   lat = ~Latitude, 
                   popup = paste(
                     "Name:", alt$Station.Name, "<br>",
                     "Address:", alt$Street.Address, "<br>",
                     "Phone #:", alt$Station.Phone, "<br>"
                     #popupImage(alt$images, src="remote")
                   ),
                   stroke = FALSE,
                   radius = 5,
                   fillOpacity = 0.7
                   ) %>%
      addMarkers(lng = ~current_loc$lon,
                 lat = ~current_loc$lat,
                 popup = "You are here") %>%
      addCircleMarkers(lng = ~current_loc$lon,
                 lat = ~current_loc$lat,
                 radius = input$range)
  })
  output$analytics <- renderPlotly({
    count_by_fuel <- altfuel%>%
      group_by(Fuel.Type.Code) %>%
      tally()
    #anal_rows <- which(altfuel$Fuel.Type.Code == input$anal_fuel_type)
    #analdata <- alt[analrows,]
    plot_ly(
      x = count_by_fuel$Fuel.Type.Code,
      y = count_by_fuel$n,
      name = "Counts",
      type = "bar",
    ) %>%
      layout(
        title = "Number of stations by fuel type"
      )
  })
  animate_data <- reactive({
    animatedata <- subset(altfuel, year == 1953)
    if (input$heat_years > 1953){
      animatedata <- subset(altfuel, year %in% c(1953:input$heat_years))
    }
    return(animatedata)
  })
  output$animate <- renderLeaflet({
      leaflet(animate_data()) %>%
        addProviderTiles("CartoDB.Positron") %>%
        addCircleMarkers(lng = ~Longitude, 
                        lat = ~Latitude,
                        stroke = FALSE,
                        radius = 5,
                        fillOpacity = 0.7,
                        color = ~pal(Fuel.Type.Code)) %>%
                        addLegend("bottomright", pal = pal, values = ~Fuel.Type.Code,
                                  title = "Fuel type",
                                  opacity = 1)
  })
  output$directory <- renderDataTable({
    shortinfo <- alt[,c('Station.Name','Street.Address','City','State','ZIP','Station.Phone','Owner.Type.Code','Access.Detail.Code')]
    shortinfo
  })
  output$timeline <- renderPlotly({
    timedata_temp <- altfuel[,c('Fuel.Type.Code','year')]
    timedata <- altfuel%>%
      group_by(year, Fuel.Type.Code) %>%
      tally()
  })
  output$gasoline_calc <- renderText({
    #distance
    dis <- gmapsdistance(origin= paste(input$start_point[[2]],"+", 
                                       input$start_point[[1]],sep = ""), 
              destination= paste(input$end_point[[2]],"+",
                                 input$end_point[[1]],sep = ""),
                  departure = "now",
                  key = "AIzaSyAZxUv1WdzxUcesZsc3xwgm2Caz2PTEMVc",
                  mode = "driving")
    distance_val <- dis$Distance #meters
    distance_time <- dis$Time #seconds
    #gas price
    gas_price <- 3
    #thing
    gas_data <- car_data %>%
      filter(Manufacturer  == input$car_brand) %>%
      filter(Model.Year  == input$car_year) %>%
      filter(Model  == input$model_selection)
    gas_data <- gas_data[,c("Conventional.Fuel.Economy.City", "Conventional.Fuel.Economy.Highway")]
    distance_val * 0.000621371 / gas_data[,1] * gas_price
  })
#  output$choro <- renderGvis({
#    geostates <- gvisGeoChart(by_state, locationvar="State", colorvar = "n",
#                 options=list(width=700, height=450,
#                              displayMode = "regions",
#                              colorAxis="{colors:[\'red']}"))
#    plot(geostates)
#  })

}


shinyApp(ui, server)
```


```{r}
#geocoding
geotest <- matrix(nrow=2,ncol=1)
geotest[1,] <- "Amsterdam"
geotest[2,] <- "Lisse"
geotest <- as.data.frame(geotest)
geotest[,1] <- as.character(geotest[,1])

mutate_geocode(geotest)

```


